---
abstract: 'shorten URLs with byst.ro (aka tinyurl.ru)'
author:
  - 'Алексей Суриков <ksuri@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: TinyURL::RU
name: TinyURL-RU
no_index:
  directory:
    - inc
    - t
recommends:
  WWW::Shorten: 0
requires:
  LWP::Simple: 0
  URI::Escape: 0
  XML::LibXML: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
